### ISSUE TITLE
.babelrc not found

### ISSUE THREAD

**Issue by dominikmayer** [practicalmeteor/mocha#30]
When I run

```
meteor test --driver-package practicalmeteor:mocha --port 3010
```

Meteor complains that it doesn't find a `.babelrc` file:

```
I20160413-01:51:38.332(2)? Creating /private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/client/.babelrc
W20160413-01:51:38.333(2)? (STDERR)           
W20160413-01:51:38.334(2)? (STDERR) /Users/dominik/.meteor/packages/meteor-tool/.1.3.1.oynoy3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160413-01:51:38.335(2)? (STDERR)                             throw(ex);
W20160413-01:51:38.335(2)? (STDERR)                                   ^
W20160413-01:51:38.344(2)? (STDERR) Error: ENOENT, no such file or directory '/private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/client/.babelrc'
W20160413-01:51:38.344(2)? (STDERR)     at Object.fs.openSync (fs.js:439:18)
W20160413-01:51:38.345(2)? (STDERR)     at Object.fs.writeFileSync (fs.js:978:15)
W20160413-01:51:38.345(2)? (STDERR)     at hot.lastHash (packages/gadicc_babel-compiler-hot.js:88:8)
W20160413-01:51:38.345(2)? (STDERR)     at packages/gadicc_babel-compiler-hot.js:190:4
W20160413-01:51:38.345(2)? (STDERR)     at packages/gadicc_babel-compiler-hot.js:625:3
W20160413-01:51:38.345(2)? (STDERR)     at /private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/.meteor/local/build/programs/server/boot.js:283:10
W20160413-01:51:38.346(2)? (STDERR)     at Array.forEach (native)
W20160413-01:51:38.346(2)? (STDERR)     at Function._.each._.forEach (/Users/dominik/.meteor/packages/meteor-tool/.1.3.1.oynoy3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160413-01:51:38.346(2)? (STDERR)     at /private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8             
```

I do have a `.babelrc` file in my project root and running the command created another one in my `client` folder.

How can I fix this?

**Comment by jsep** [comment]
hello @dominikmayer 

I think the the problem is with [gadicc:babel-compiler-hot](https://atmospherejs.com/gadicc/babel-compiler-hot) pakckage and not `practicalmeteor:mocha`.

**Comment by dominikmayer** [comment]
Ah, thanks for the information. I was thinking about this package because the other one doesn't cause any problems when running `meteor`. I added the [issue](https://github.com/gadicc/meteor-react-hotloader/issues/37) over there.
