### ISSUE TITLE
Error on browser.url

### ISSUE THREAD

**Issue by lorensr** [practicalmeteor/mocha#38]
Test:

```
describe('app loads', function () {
  beforeEach(function () {
    browser.url('http://localhost:3000');
  });

  it('loads @dev', function () {
    assert.isOk(true);
  });
});
```

The error: 

```
[chimp] Running...
Unhandled rejection ReferenceError: Symbol is not defined
    at Object.applyPrototype (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/wdio-sync/build/index.js:387:71)
    at /usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/wdio-sync/build/index.js:338:52
    at tryCatcher (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/usr/local/lib/node_modules/chimp/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```

Repro:

```
> meteor create chimp-symbol
> meteor add practicalmeteor:mocha
> # add above test file
> chimp --ddp=http://localhost:3000 --watch --mocha --path=tests
```

https://github.com/lorensr/chimp-symbol

**Comment by lorensr** [comment]
Sorry, wrong repo 😅
