### ISSUE TITLE
TypeError when running tests on Windows 10 with Meteor 1.3.3.1

### ISSUE THREAD

**Issue by asdfjackal** [practicalmeteor/mocha#51]
When I run the meteor test command with the practicalmeteor:mocha driver I recieve the following error log and an exit code of 8:

```
W20160619-22:24:12.067(-4)? (STDERR) C:\Users\REDACTED\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160619-22:24:12.073(-4)? (STDERR)                                            throw(ex);
W20160619-22:24:12.076(-4)? (STDERR)                                                  ^
W20160619-22:24:12.079(-4)? (STDERR) TypeError: Cannot call method 'push' of undefined
W20160619-22:24:12.082(-4)? (STDERR)     at meteorInstall.node_modules.meteor.practicalmeteor:mocha-core.node_modules.mocha.lib.mocha.js (node_modules/meteor/practicalmeteor:mocha-core/node_modules/mocha/lib/mocha.js:28:1)
W20160619-22:24:12.085(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160619-22:24:12.088(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160619-22:24:12.091(-4)? (STDERR)     at meteorInstall.node_modules.meteor.practicalmeteor:mocha-core.node_modules.mocha.index.js (node_modules/meteor/practicalmeteor:mocha-core/node_modules/mocha/index.js:3:1)
W20160619-22:24:12.108(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160619-22:24:12.116(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160619-22:24:12.119(-4)? (STDERR)     at meteorInstall.node_modules.meteor.practicalmeteor:mocha-core.server.js (packages/practicalmeteor:mocha-core/server.js:2:1)
W20160619-22:24:12.122(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160619-22:24:12.125(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160619-22:24:12.137(-4)? (STDERR)     at node_modules/meteor/practicalmeteor:mocha-core/node_modules/mocha/node_modules/growl/lib/growl.js:234:1
```

**Comment by walliski** [comment]
:+1: for windows 8.1. Just updated meteor to 1.3.3.1 and this broke in the process I think.

Package changes:

```
-practicalmeteor:mocha@2.4.5_2
-practicalmeteor:mocha-core@0.1.4
+practicalmeteor:mocha@2.4.5_3
+practicalmeteor:mocha-core@1.0.0
```

perhaps has something to do with it?

**Comment by jsep** [comment]
Hello @asdfjackal and @walliski I just release a new version should solve this issue:

Run this:

```
meteor add practicalmeteor:mocha@=2.4.5-rc5.1 
```

**Comment by gladiussdv** [comment]
Hello @jsep! I had the same error that mentioned by @asdfjackal. I have error while I am installing the package on windows 10: 
meteor add practicalmeteor:mocha@=2.4.5-rc5.1
 => Errors while adding packages:

While checking for practicalmeteor:mocha@2.4.5-rc5.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

I have following versions of frameworks/environments:
G:\work\meteor\simple-todos>meteor --version
Meteor 1.3.4
G:\work\meteor\simple-todos>node --version
v4.2.6
G:\work\meteor\simple-todos>npm --version
3.9.5

**Comment by jsep** [comment]
Hello @gladiussdv there is an error with meteor, I can't publish the package for windows architecture, not sure why :confused:

**Comment by walliski** [comment]
@jsep Any progress :) ?

**Comment by jsep** [comment]
Hello @walliski @gladiussdv, @asdfjackal,

Now you can try the release candidate:

 `meteor add practicalmeteor:mocha@=2.4.5-rc5.5`

**Comment by gladiussdv** [comment]
Thanks! It works!!!
