### ISSUE TITLE
Error: There is already a collection named "mochaServerRunEvents"

### ISSUE THREAD

**Issue by ckiely91** [practicalmeteor/mocha#76]
Hey there,

Trying to run the following: `meteor test --driver-package=practicalmeteor:mocha` results in the following error that subsequently exits:

```
W20161209-14:06:39.565(11)? (STDERR) /Users/christian/.meteor/packages/meteor-tool/.1.4.2_3.1hru9ra++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161209-14:06:39.565(11)? (STDERR) 						throw(ex);
W20161209-14:06:39.565(11)? (STDERR) 						^
W20161209-14:06:39.566(11)? (STDERR)
W20161209-14:06:39.566(11)? (STDERR) Error: There is already a collection named "mochaServerRunEvents"
W20161209-14:06:39.567(11)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:244:15)
W20161209-14:06:39.567(11)? (STDERR)     at new MochaRunner (packages/practicalmeteor_mocha/meteor/src/lib/MochaRunner.coffee:28:30)
W20161209-14:06:39.567(11)? (STDERR)     at Function.MochaRunner.get (packages/practicalmeteor_mocha/meteor/src/lib/MochaRunner.coffee:17:33)
W20161209-14:06:39.568(11)? (STDERR)     at meteorInstall.node_modules.meteor.practicalmeteor:mocha.meteor.src.lib.MochaRunner.coffee.js (packages/practicalmeteor_mocha/meteor/src/lib/MochaRunner.coffee:174:30)
W20161209-14:06:39.569(11)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161209-14:06:39.569(11)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161209-14:06:39.570(11)? (STDERR)     at meteorInstall.node_modules.meteor.practicalmeteor:mocha.meteor.src.lib.MochaRunner.coffee (/private/var/folders/7g/w66hp0rs0bb4x0chyv8p1pb00000gn/T/meteor-test-run11ndyts/.meteor/local/build/programs/server/packages/practicalmeteor_mocha.js:99:18)
W20161209-14:06:39.571(11)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161209-14:06:39.572(11)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161209-14:06:39.572(11)? (STDERR)     at Module.Mp.import (/Users/christian/.meteor/packages/modules/.0.7.7.jvu3qu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
```

Running Meteor 1.4.2.3, Mac OS 10.12.1. Let me know if you need any more info. I'd appreciate any help on the above!

**Comment by ckiely91** [comment]
Solved the issue - I mistakenly still had the avital:mocha package added to my project.
